export type GlobalMapPoint = {
  topEm: number;
  leftEm: number;
  organization: string;
  study: string;
  location: string;
  placement: "left" | "right";
};

export const GLOBAL_MAP_POINTS: GlobalMapPoint[] = [
  {
    topEm: 23,
    leftEm: 76.5,
    organization: "CRCHUM & CPAS institutes",
    study: "Multi-Drug Resistant TB",
    location: "Vietnam",
    placement: "left",
  },
  {
    topEm: 24,
    leftEm: 76.5,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "Vietnam",
    placement: "left",
  },
  {
    topEm: 20.5,
    leftEm: 69,
    organization: "John Hopkins University",
    study: "TB",
    location: "India",
    placement: "left",
  },
  {
    topEm: 18.5,
    leftEm: 70,
    organization: "World Health Partners",
    study: "TB",
    location: "Bihar, India",
    placement: "left",
  },
  {
    topEm: 11.5,
    leftEm: 49.6,
    organization: "Geneva University Hospitals (HUG)",
    study: "Pediatric Bronchiolitis",
    location: "Geneva, Switzerland",
    placement: "right",
  },
  {
    topEm: 14.5,
    leftEm: 46,
    organization: "Hospital de Navarra",
    study: "COVID-19 other respiratory diseases",
    location: "Navarra-Pamplona, Spain",
    placement: "right",
  },
  {
    topEm: 13.5,
    leftEm: 47,
    organization: "Sewanee University",
    study: "COVID-19",
    location: "Navarra-Pamplona, Spain",
    placement: "left",
  },
  {
    topEm: 11.5,
    leftEm: 28,
    organization: "CRCHUM & McGill University",
    study: "COVID-19 and Cystic Fibrosis",
    location: "Montreal, Canada",
    placement: "right",
  },
  {
    topEm: 14,
    leftEm: 27.5,
    organization: "New York University",
    study: "RCC",
    location: "New York, USA",
    placement: "right",
  },
  {
    topEm: 13.5,
    leftEm: 25.5,
    organization: "University of Pittsburgh",
    study: "TB",
    location: "Pittsburgh, USA",
    placement: "right",
  },
  {
    topEm: 32,
    leftEm: 57,
    organization: "University of Navarra",
    study: "Malaria",
    location: "Mozambique",
    placement: "left",
  },
  {
    topEm: 11.5,
    leftEm: 24,
    organization: "University of Minnesota",
    study: "RCC",
    location: "Minnesota, USA",
    placement: "right",
  },
  {
    topEm: 18,
    leftEm: 79,
    organization: "Fudan University",
    study: "TB",
    location: "Shanghai, China",
    placement: "left",
  },
  {
    topEm: 15,
    leftEm: 81,
    organization: "Asan Medical Center",
    study: "RCC",
    location: "Korea",
    placement: "left",
  },
  {
    topEm: 10.1,
    leftEm: 50,
    organization: "ARCIM institute",
    study: "Pediatric bronchiolitis",
    location: "Germany",
    placement: "right",
  },
  {
    topEm: 37,
    leftEm: 87,
    organization: "John Hunter Hospital",
    study: "Asthma",
    location: "New South Wales, Australia",
    placement: "left",
  },
  {
    topEm: 30,
    leftEm: 34,
    organization: "University of Montreal (CRCHUM)",
    study: "COVID-19",
    location: "Brazil",
    placement: "right",
  },
  {
    topEm: 9,
    leftEm: 46.5,
    organization: "University of Hull",
    study: "GERd",
    location: "Hull, UK",
    placement: "left",
  },
  {
    topEm: 15.5,
    leftEm: 15.5,
    organization: "FEND",
    study: "RCC",
    location: "USA",
    placement: "right",
  },
  {
    topEm: 11.5,
    leftEm: 16.5,
    organization: "PAI Life Sciences",
    study: "NTM",
    location: "Seattle, USA",
    placement: "right",
  },
  {
    topEm: 13,
    leftEm: 15.6,
    organization: "Oregon Health Science University",
    study: "NTM",
    location: "Oregon, USA",
    placement: "right",
  },
  {
    topEm: 13.5,
    leftEm: 45.5,
    organization: "Hospital del Sol",
    study: "COVID-19",
    location: "Spain",
    placement: "left",
  },
  {
    topEm: 25.5,
    leftEm: 54.5,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "Uganda",
    placement: "left",
  },
  {
    topEm: 22,
    leftEm: 42.5,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "Gambia",
    placement: "left",
  },
  {
    topEm: 9.9,
    leftEm: 47.3,
    organization: "Imperial College London",
    study: "RCC",
    location: "UK",
    placement: "left",
  },
  {
    topEm: 15.5,
    leftEm: 24,
    organization: "McGill University",
    study: "CHF",
    location: "USA",
    placement: "right",
  },
  {
    topEm: 18,
    leftEm: 25,
    organization: "UF-EPI (Glenn Morris)",
    study: "COVID-19",
    location: "Florida, USA",
    placement: "right",
  },
  {
    topEm: 26.5,
    leftEm: 54,
    organization: "John Hopkins University",
    study: "TB",
    location: "Uganda",
    placement: "left",
  },
  {
    topEm: 29,
    leftEm: 25.5,
    organization: "Montreal (CRCHUM) & McGill University",
    study: "TB",
    location: "Peru",
    placement: "left",
  },
  {
    topEm: 32.5,
    leftEm: 59.5,
    organization:
      "The University of Montreal Hospital Research Centre (CRCHUM)",
    study: "TB",
    location: "Madagascar",
    placement: "right",
  },
  {
    topEm: 28.5,
    leftEm: 57,
    organization:
      "The University of Montreal Hospital Research Centre (CRCHUM)",
    study: "TB",
    location: "Tanzania",
    placement: "left",
  },
  {
    topEm: 23,
    leftEm: 81,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "Phillippines",
    placement: "left",
  },
  {
    topEm: 36,
    leftEm: 53.5,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "South Africa",
    placement: "left",
  },
  {
    topEm: 22,
    leftEm: 68,
    organization: "Rapid Research in Diagnostics Development for TB Network",
    study: "TB",
    location: "India",
    placement: "left",
  },
  {
    topEm: 32.5,
    leftEm: 33,
    organization: "Ribeirao Medical School",
    study: "Pediatric RCC",
    location: "Brazil",
    placement: "left",
  },
];
